SELECT TOP (1000) [MaKH]
      ,[Ten]
      ,[Sdt]
      ,[SoNha]
      ,[Duong]
      ,[Phuong]
      ,[Quan]
      ,[ThanhPho]
      ,[Email]
      ,[MatKhau]
      ,[GioiTinh]
      ,[NgaySinh]
      ,[TikiXu]
  FROM [Tiki].[dbo].[KhachHang]